### ISSUE TITLE
Assigning a fixed value to variable in every nested loop

### ISSUE THREAD

**Issue by jacobxk** [miguel-sorrel/cdcatR#1]
Hi, thanks for this implementation of CD-CAT. When I went through the codes in cdcat.R, I found the following replacement on `res` in every nested loop. It seems that the `res` was set to 1 on each execution. Is it on purpose?

R/cdcat.R
```r
p.xi <- matrix(LC.prob[jjcatGDI,], ncol = L)
p.xi.aj1_GDI <- matrix(0, nrow = L, ncol = length(IP))
for(l in 1L:L){
    for(jj in 1L:length(IP)){
        res <- 1
        p.xi.aj1_GDI[l,jj] <- res * (p.xi[jj, l]^IP[jj]) * ((1 - p.xi[jj, l])^(1 - IP[jj]))
        res <- p.xi.aj1_GDI[l, jj]
    }
}
```

**Comment by miguel-sorrel** [comment]
Hi! Thank you so much for your interest in the package. Sorry that it took me so long to respond to you - I didn't see the message.  

Please note that "res" is not used in the code after that loop. We use "p.xi.aj1_GDI" in the code that goes after that to compute the likelihood (not res):
p.xi.aj_GDI <- (t(as.matrix(apply(p.xi.aj1_GDI, 1, prod))))

In the next version, I will remove that to avoid confusion. This is an "easter egg" from a previous version of the code where I computed the likelihood inside the loop. 

Thank you again for looking at it so carefully. I hope you find it useful. 
Best,
Miguel

**Comment by jacobxk** [comment]
Thanks for your efforts on this implementation of CD-CAT. It saves me lots of time to figure all things out in the journal articles!

**Comment by miguel-sorrel** [comment]
No problem! :)
